spring:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-service-db
    username: root
    password: 212109
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8888

  kafka:
    bootstrap-servers: localhost:9092