spring:
  application:
    name: gateway-service

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

server:
  port: 8762