version: "3.7"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:

  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_CLUSTER_NAME: test
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  mysql-auth-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth_db
    networks:
      - kafka-net

  mysql-library-web-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library_web_db
    networks:
      - kafka-net

  mysql-library-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=library_db
    networks:
      - kafka-net
                                                          #GATEWAY
  gateway:
    build:
      context: ../gateway-service
      dockerfile: ../gateway-service/dockerfile
    environment:
      AUTH_SERVICE_URL: http://auth-service:8400
      LIBRARY_WEB_SERVICE_URL: http://library-web-service:8091
    ports:
      - "8762:8762"
    links:
      - library-web-service
      - auth-service
    restart: always
    depends_on:
      - kafka
    networks:
      - kafka-net
                                                         #AUTH-SERVICE
  auth-service:
    build:
      context: ../authentication-service
      dockerfile: ../authentication-service/dockerfile
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-auth-service:3306/auth_db
    depends_on:
      - mysql-auth-service
      - kafka
    restart: always
    networks:
      - kafka-net
    ports:
      - "8400:8400"
                                                         #LIBRARY-WEB-SERVICE
  library-web-service:
    build:
      context: ../library-web-service
      dockerfile: ../library-web-service/dockerfile
    environment:
      - LIBRARY_SERVICE_URL=http://library-service:8888/storage
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-library-web-service:3306/library_web_db
    depends_on:
      - kafka
    restart: always
    networks:
      - kafka-net
    links:
      - library-service

    ports:
      - "8091:8091"
                                                         #LIBRARY-SERVICE
  library-service:
    build:
      context: ../library-service
      dockerfile: ../library-service/dockerfile
    environment:
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-library-service:3306/library_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8888:8888"
    depends_on:
      - mysql-library-service
      - kafka
    restart: always
    networks:
      - kafka-net

