spring:
  application:
    name: authentication-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: 212109
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

server:
  port: 8400

springdoc:
  api-docs:
    path: auth/swagger-ui/index.html